language: node_js

node_js:
    - "node"

env:
    - NODE_ENV=TEST

python:
    - "3.6"

addons:
  apt:
    packages:
    - jq

install:
    - npm install -g json

services:
  - docker

script:
  - docker login -u${user} -p${pass}
  - chmod +x *.sh
  - ./test.sh arkriggins/todowrangler

branches:
  only:
    - travis_ci
