apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-app-monitor-test
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: k8s-app-monitor-test
    spec:
      containers:
      - image: jimmysong/k8s-app-monitor-test:latest
        imagePullPolicy: Always
        name : app
        ports:
        - containerPort: 3000
        env: 
        - name: APP_PORT
          value: "3000"
        - name: SERVICE_NAME
          value: "k8s-app-monitor-test"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app-monitor-test
  labels:
    k8s-svc: k8s-app-monitor-test
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    k8s-app: k8s-app-monitor-test
